### ISSUE TITLE
Conflict with Origins and End Respawn Anchor

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [Mikndesu/EndRespawnAnchorMod#7]
Hi!

I've been using this mod for a while and wanted to set it up alongside Origins on Fabric. However, due to the way the mod modify spawns, it conflicts with Apoli, the library behind Origins and crashes the game on World Join.

## Information

- Loader: Fabric
- Game Version: 1.20.1
- Mod List:
  - Origins (1.10.0)
  - Fabric API (0.92.1+1.20.1)
  - End Respawn Anchor (1.0.0)
  
## How to reproduce

1. Install Fabric on Minecraft 1.20.1
1. Add Origins in `.minecraft/mods`
1. Add End Respawn Anchor in `.minecraft/mods`
1. Add Fabric API in `.minecraft/mods`
1. Create a world or join an existing world
1. The Game should crash when joining the world. 

## Trace

```
// Joining World
[20:37:06] [Render thread/INFO]: Loaded 7 recipes
[20:37:06] [Render thread/INFO]: Loaded 1273 advancements
[20:37:06] [Render thread/INFO]: Finished loading powers from data files. Registry contains 76 powers.
[20:37:06] [Render thread/INFO]: Finished loading origins from data files. Registry contains 11 origins.
[20:37:06] [Render thread/INFO]: Trying to read layer file: origins:origin
[20:37:06] [Render thread/INFO]: Finished loading origin layers from data files. Read 1 layers.
[20:37:06] [Render thread/INFO]: Loaded 0 global power sets.

// Warn that shows up on loading
[20:37:08] [Render thread/WARN]: @Redirect conflict. Skipping apoli.mixins.json:LoginMixin from mod apoli->@Redirect::preventEndExitSpawnPointSetting(Lnet/minecraft/class_3222;Lnet/minecraft/class_5321;Lnet/minecraft/class_2338;FZZLnet/minecraft/class_3222;Z)V with priority 800, already redirected by end_respawn_anchor.mixins.json:PlayerListMixin from mod end_respawn_anchor->@Redirect::redirect_setRespawnPosition(Lnet/minecraft/class_3222;Lnet/minecraft/class_5321;Lnet/minecraft/class_2338;FZZLnet/minecraft/class_3222;Z)V with priority 1000

// Immediatly after warning, the game crashes, throwing this exception
[20:37:08] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Starting integrated server
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:169) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:169) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1244) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3324 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_310.method_29603(class_310.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41889(class_7196.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_41847(class_525.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_45683(class_525.java:451) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41892(class_7196.java:303) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:451) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_310.method_29603(class_310.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41889(class_7196.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_41847(class_525.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_45683(class_525.java:451) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41892(class_7196.java:303) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:451) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector preventEndExitSpawnPointSetting(Lnet/minecraft/class_3222;Lnet/minecraft/class_5321;Lnet/minecraft/class_2338;FZZLnet/minecraft/class_3222;Z)V in apoli.mixins.json:LoginMixin from mod apoli failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Apoli-1.20.1-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_310.method_29603(class_310.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2094) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41889(class_7196.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_41847(class_525.java:469) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_45683(class_525.java:451) ~[client-intermediary.jar:?]
	at net.minecraft.class_7196.method_41892(class_7196.java:303) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:451) ~[client-intermediary.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:404) ~[client-intermediary.jar:?]
	at net.minecraft.class_4185.method_25306(class_4185.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_4264.method_25348(class_4264.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:189) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:409) ~[client-intermediary.jar:?]
	... 17 more
```

Hope you'll find a way to fix it :)

Best regards.

**Comment by Mikndesu** [comment]
Hi, Zhaith-Izaliel, thanks for your detailed report! Sorry for the late reply. I have published a new version on both CurseForge and Modrinth that solves conflicts. Hope you enjoy my mod!

**Comment by Zhaith-Izaliel** [comment]
Hi, thank you for the update! I've been able to test it with Origins and it works wonderfully, I'll close this issue as resolved!
