### ISSUE TITLE
Version 1.1.0 respawn failed

### ISSUE THREAD

**Issue by Plank441** [Mikndesu/EndRespawnAnchorMod#8]
Hello I tested version 1.1.0 and the game crashes when I either set up the anchor in the end and jumped into the void or died to intentional game design by setting up in the overworld. I also tested the latest version and I couldn't charge the anchor with pearls or eyes.

**Comment by Mikndesu** [comment]
Hello Plank441, could you post a crash report if possible to investigate the issue?

**Comment by Plank441** [comment]
When the anchor gets activated in the overworld and the player can't respawn at the world spawn after death.

[14:34:46] [Render thread/INFO]: [System] [CHAT] Sea_lion_pup was killed by [Intentional Game Design]
[14:34:51] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2799@5801d264, suppressing error
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at java.util.Optional.of(Optional.java:113) ~[?:?]
	at net.minecraft.class_3324.redirect$zza000$end_respawn_anchor$redirect_position(class_3324.java:1026) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14556(class_3324.java:468) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12068(class_3244.java:1590) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_12120(class_2799.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_2799.method_11054(class_2799.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Mikndesu** [comment]
Thank you Plank441, could you also tell me the minecraft version, the ModLoader and other mods if installed with?

**Comment by Plank441** [comment]
![multiMC](https://github.com/Mikndesu/EndRespawnAnchorMod/assets/174599858/deefad3c-8b7e-4951-82dc-53f2d6b0d281)

**Comment by Plank441** [comment]
I'm using fabric version 1.20.2 with cloth config, fabric api and mod menu in unmodded vanilla.

![image](https://github.com/Mikndesu/EndRespawnAnchorMod/assets/174599858/41f2bdfa-f10e-4b47-a0ab-a730c07d19f7)

**Comment by Mikndesu** [comment]
I have published a new version on both CurseForge and Modrinth that solves the crash issue, and I'll address another issue concerning the latest version. Thank you for your report!

**Comment by Plank441** [comment]
thankyou for sorting out an older version. The only problem I have now is mining the anchor back because its like bedrock.

**Comment by Mikndesu** [comment]
It has the same hardness and blast resistance with the Respawn Anchor, so correct tools(diamonds or higher) should be used to mine as well.

**Comment by Plank441** [comment]
I tried all the picks including netherite with efficiency 5 and couldn't break it.

**Comment by Mikndesu** [comment]
Many thanks, I've published a new version. I didn't recognise this problem :)

**Comment by Plank441** [comment]
All sorted. Now I have anchors for all 3 dimensions and can do without beds. Thanks alot.
